
---
- name: Deploy ELK
  hosts: docker
  become: yes
  tasks:
  - name: Increase vm.max_map_count on elasticsearch nodes
    shell: sysctl -w vm.max_map_count=262144

  - name: Deploy ELK from a compose file
    docker_stack:
      state: present
      name: logging
      compose:
        - /opt/fase2/logging/docker-log.yml