---
- name: Preparing deploy
  hosts: docker
  become: yes
  tasks:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: latest

  - name: Install Python pip
    yum:
      name: python-pip

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install Docker module for Python
    pip:
      name: docker
      state: latest

  - name: Install Docker Compose module
    pip:
      name: docker-compose
      state: latest

  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    
  - name: Install Docker itself
    package:
      name: docker-ce
      state: latest

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Init swarm service
    docker_swarm:
      state: present

  - name: Install jsondiff
    pip:
      name: jsondiff
      state: latest

  - name: Install Git
    yum:
      name: git
      state: latest
      
  - name: Clone the app repo
    git:
      repo: 'https://github.com/rizalbayyu/fase2.git'
      dest: /opt/fase2
      version: master
