---
- name: Preparing deploy
  hosts: docker
  become: yes
  tasks:
  - name: Install EPEL repository
    yum:
      name: epel-release
      state: latest

  - name: Install Python pip
    yum:
      name: python-pip

  - name: Upgraade pip
    pip:
     name: pip
     extra_args: --upgrade

  - name: Install Docker module for Python
    pip:
      name: docker
      state: latest

  - name: Install Docker Compose module
    pip:
      name: docker-compose
      state: latest

  - name: Enable the Docker daemon in systemd
      systemd:
        name: docker
        enabled: yes
        masked: no

  - name: Start the Docker daemon
      systemd:
        name: docker
        state: started
        masked: no

  - name: Install Git
    yum:
      name: git
      state: latest
  - name: Clone the app repo
    git:
      repo: 'https://github.com/rizalbayyu/fase2.git'
      dest: /opt/fase2
      version: master
